sudo: false
cache: pip
language: python

python:
  - "2.7"

install:
  - pip install .
  - pip install coveralls
  - pip install pytest pytest-cov pytest-flake8

script:
  - py.test --cov=setuptools_odoo --flake8

after_success:
  - coveralls
