name: CI

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: "actions/checkout@v2"
        with:
          # some tests work on the git history so we need all of it!
          fetch-depth: 0
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: python -m pip install tox tox-gh-actions
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: python -m tox
      - name: Coveralls
        if: matrix.python-version != 2.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install coveralls
          coveralls
  deploy:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - tests
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
      - name: Install pypa/build
        run: python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
